/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.adjecti.meeting.model.impl;

import com.adjecti.meeting.model.Asset;
import com.adjecti.meeting.model.AssetModel;
import com.adjecti.meeting.model.AssetSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Asset service. Represents a row in the &quot;meeting_Asset&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AssetModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AssetImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AssetImpl
 * @generated
 */
@JSON(strict = true)
public class AssetModelImpl extends BaseModelImpl<Asset> implements AssetModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a asset model instance should use the <code>Asset</code> interface instead.
	 */
	public static final String TABLE_NAME = "meeting_Asset";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"assetId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"companyId", Types.BIGINT},
		{"userId", Types.BIGINT}, {"userName", Types.VARCHAR},
		{"createDate", Types.TIMESTAMP}, {"modifiedDate", Types.TIMESTAMP},
		{"name", Types.VARCHAR}, {"assetModel", Types.VARCHAR},
		{"purchaseDate", Types.VARCHAR}, {"serialNo", Types.VARCHAR},
		{"status", Types.BOOLEAN}, {"roomAssigned", Types.BOOLEAN}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("name", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assetModel", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("purchaseDate", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("serialNo", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("status", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("roomAssigned", Types.BOOLEAN);
	}

	public static final String TABLE_SQL_CREATE =
		"create table meeting_Asset (uuid_ VARCHAR(75) null,assetId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,name VARCHAR(75) null,assetModel VARCHAR(75) null,purchaseDate VARCHAR(75) null,serialNo VARCHAR(75) null,status BOOLEAN,roomAssigned BOOLEAN)";

	public static final String TABLE_SQL_DROP = "drop table meeting_Asset";

	public static final String ORDER_BY_JPQL = " ORDER BY asset.name ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY meeting_Asset.name ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ASSETMODEL_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long GROUPID_COLUMN_BITMASK = 4L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long NAME_COLUMN_BITMASK = 8L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ROOMASSIGNED_COLUMN_BITMASK = 16L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long SERIALNO_COLUMN_BITMASK = 32L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long UUID_COLUMN_BITMASK = 64L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static Asset toModel(AssetSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Asset model = new AssetImpl();

		model.setUuid(soapModel.getUuid());
		model.setAssetId(soapModel.getAssetId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setName(soapModel.getName());
		model.setAssetModel(soapModel.getAssetModel());
		model.setPurchaseDate(soapModel.getPurchaseDate());
		model.setSerialNo(soapModel.getSerialNo());
		model.setStatus(soapModel.isStatus());
		model.setRoomAssigned(soapModel.isRoomAssigned());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static List<Asset> toModels(AssetSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Asset> models = new ArrayList<Asset>(soapModels.length);

		for (AssetSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public AssetModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _assetId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setAssetId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _assetId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Asset.class;
	}

	@Override
	public String getModelClassName() {
		return Asset.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Asset, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Asset, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Asset, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Asset)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Asset, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Asset, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Asset)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Asset, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Asset, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Asset>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Asset.class.getClassLoader(), Asset.class, ModelWrapper.class);

		try {
			Constructor<Asset> constructor =
				(Constructor<Asset>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Asset, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Asset, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Asset, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Asset, Object>>();
		Map<String, BiConsumer<Asset, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Asset, ?>>();

		attributeGetterFunctions.put("uuid", Asset::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Asset, String>)Asset::setUuid);
		attributeGetterFunctions.put("assetId", Asset::getAssetId);
		attributeSetterBiConsumers.put(
			"assetId", (BiConsumer<Asset, Long>)Asset::setAssetId);
		attributeGetterFunctions.put("groupId", Asset::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Asset, Long>)Asset::setGroupId);
		attributeGetterFunctions.put("companyId", Asset::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Asset, Long>)Asset::setCompanyId);
		attributeGetterFunctions.put("userId", Asset::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Asset, Long>)Asset::setUserId);
		attributeGetterFunctions.put("userName", Asset::getUserName);
		attributeSetterBiConsumers.put(
			"userName", (BiConsumer<Asset, String>)Asset::setUserName);
		attributeGetterFunctions.put("createDate", Asset::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Asset, Date>)Asset::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Asset::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Asset, Date>)Asset::setModifiedDate);
		attributeGetterFunctions.put("name", Asset::getName);
		attributeSetterBiConsumers.put(
			"name", (BiConsumer<Asset, String>)Asset::setName);
		attributeGetterFunctions.put("assetModel", Asset::getAssetModel);
		attributeSetterBiConsumers.put(
			"assetModel", (BiConsumer<Asset, String>)Asset::setAssetModel);
		attributeGetterFunctions.put("purchaseDate", Asset::getPurchaseDate);
		attributeSetterBiConsumers.put(
			"purchaseDate", (BiConsumer<Asset, String>)Asset::setPurchaseDate);
		attributeGetterFunctions.put("serialNo", Asset::getSerialNo);
		attributeSetterBiConsumers.put(
			"serialNo", (BiConsumer<Asset, String>)Asset::setSerialNo);
		attributeGetterFunctions.put("status", Asset::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Asset, Boolean>)Asset::setStatus);
		attributeGetterFunctions.put("roomAssigned", Asset::getRoomAssigned);
		attributeSetterBiConsumers.put(
			"roomAssigned", (BiConsumer<Asset, Boolean>)Asset::setRoomAssigned);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_uuid = uuid;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalUuid() {
		return getColumnOriginalValue("uuid_");
	}

	@JSON
	@Override
	public long getAssetId() {
		return _assetId;
	}

	@Override
	public void setAssetId(long assetId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetId = assetId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_groupId = groupId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalGroupId() {
		return GetterUtil.getLong(this.<Long>getColumnOriginalValue("groupId"));
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_companyId = companyId;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalCompanyId() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("companyId"));
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public String getName() {
		if (_name == null) {
			return "";
		}
		else {
			return _name;
		}
	}

	@Override
	public void setName(String name) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_name = name;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalName() {
		return getColumnOriginalValue("name");
	}

	@JSON
	@Override
	public String getAssetModel() {
		if (_assetModel == null) {
			return "";
		}
		else {
			return _assetModel;
		}
	}

	@Override
	public void setAssetModel(String assetModel) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_assetModel = assetModel;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalAssetModel() {
		return getColumnOriginalValue("assetModel");
	}

	@JSON
	@Override
	public String getPurchaseDate() {
		if (_purchaseDate == null) {
			return "";
		}
		else {
			return _purchaseDate;
		}
	}

	@Override
	public void setPurchaseDate(String purchaseDate) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_purchaseDate = purchaseDate;
	}

	@JSON
	@Override
	public String getSerialNo() {
		if (_serialNo == null) {
			return "";
		}
		else {
			return _serialNo;
		}
	}

	@Override
	public void setSerialNo(String serialNo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_serialNo = serialNo;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public String getOriginalSerialNo() {
		return getColumnOriginalValue("serialNo");
	}

	@JSON
	@Override
	public boolean getStatus() {
		return _status;
	}

	@JSON
	@Override
	public boolean isStatus() {
		return _status;
	}

	@Override
	public void setStatus(boolean status) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_status = status;
	}

	@JSON
	@Override
	public boolean getRoomAssigned() {
		return _roomAssigned;
	}

	@JSON
	@Override
	public boolean isRoomAssigned() {
		return _roomAssigned;
	}

	@Override
	public void setRoomAssigned(boolean roomAssigned) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_roomAssigned = roomAssigned;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public boolean getOriginalRoomAssigned() {
		return GetterUtil.getBoolean(
			this.<Boolean>getColumnOriginalValue("roomAssigned"));
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Asset.class.getName()));
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Asset.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Asset toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Asset>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AssetImpl assetImpl = new AssetImpl();

		assetImpl.setUuid(getUuid());
		assetImpl.setAssetId(getAssetId());
		assetImpl.setGroupId(getGroupId());
		assetImpl.setCompanyId(getCompanyId());
		assetImpl.setUserId(getUserId());
		assetImpl.setUserName(getUserName());
		assetImpl.setCreateDate(getCreateDate());
		assetImpl.setModifiedDate(getModifiedDate());
		assetImpl.setName(getName());
		assetImpl.setAssetModel(getAssetModel());
		assetImpl.setPurchaseDate(getPurchaseDate());
		assetImpl.setSerialNo(getSerialNo());
		assetImpl.setStatus(isStatus());
		assetImpl.setRoomAssigned(isRoomAssigned());

		assetImpl.resetOriginalValues();

		return assetImpl;
	}

	@Override
	public int compareTo(Asset asset) {
		int value = 0;

		value = getName().compareTo(asset.getName());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof Asset)) {
			return false;
		}

		Asset asset = (Asset)object;

		long primaryKey = asset.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_setModifiedDate = false;

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<Asset> toCacheModel() {
		AssetCacheModel assetCacheModel = new AssetCacheModel();

		assetCacheModel.uuid = getUuid();

		String uuid = assetCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			assetCacheModel.uuid = null;
		}

		assetCacheModel.assetId = getAssetId();

		assetCacheModel.groupId = getGroupId();

		assetCacheModel.companyId = getCompanyId();

		assetCacheModel.userId = getUserId();

		assetCacheModel.userName = getUserName();

		String userName = assetCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			assetCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			assetCacheModel.createDate = createDate.getTime();
		}
		else {
			assetCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			assetCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			assetCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		assetCacheModel.name = getName();

		String name = assetCacheModel.name;

		if ((name != null) && (name.length() == 0)) {
			assetCacheModel.name = null;
		}

		assetCacheModel.assetModel = getAssetModel();

		String assetModel = assetCacheModel.assetModel;

		if ((assetModel != null) && (assetModel.length() == 0)) {
			assetCacheModel.assetModel = null;
		}

		assetCacheModel.purchaseDate = getPurchaseDate();

		String purchaseDate = assetCacheModel.purchaseDate;

		if ((purchaseDate != null) && (purchaseDate.length() == 0)) {
			assetCacheModel.purchaseDate = null;
		}

		assetCacheModel.serialNo = getSerialNo();

		String serialNo = assetCacheModel.serialNo;

		if ((serialNo != null) && (serialNo.length() == 0)) {
			assetCacheModel.serialNo = null;
		}

		assetCacheModel.status = isStatus();

		assetCacheModel.roomAssigned = isRoomAssigned();

		return assetCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Asset, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(4 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Asset, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Asset, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Asset)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Asset, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Asset, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Asset, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Asset)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Asset>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private String _uuid;
	private long _assetId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private String _name;
	private String _assetModel;
	private String _purchaseDate;
	private String _serialNo;
	private boolean _status;
	private boolean _roomAssigned;

	public <T> T getColumnValue(String columnName) {
		columnName = _attributeNames.getOrDefault(columnName, columnName);

		Function<Asset, Object> function = _attributeGetterFunctions.get(
			columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((Asset)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("uuid_", _uuid);
		_columnOriginalValues.put("assetId", _assetId);
		_columnOriginalValues.put("groupId", _groupId);
		_columnOriginalValues.put("companyId", _companyId);
		_columnOriginalValues.put("userId", _userId);
		_columnOriginalValues.put("userName", _userName);
		_columnOriginalValues.put("createDate", _createDate);
		_columnOriginalValues.put("modifiedDate", _modifiedDate);
		_columnOriginalValues.put("name", _name);
		_columnOriginalValues.put("assetModel", _assetModel);
		_columnOriginalValues.put("purchaseDate", _purchaseDate);
		_columnOriginalValues.put("serialNo", _serialNo);
		_columnOriginalValues.put("status", _status);
		_columnOriginalValues.put("roomAssigned", _roomAssigned);
	}

	private static final Map<String, String> _attributeNames;

	static {
		Map<String, String> attributeNames = new HashMap<>();

		attributeNames.put("uuid_", "uuid");

		_attributeNames = Collections.unmodifiableMap(attributeNames);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("uuid_", 1L);

		columnBitmasks.put("assetId", 2L);

		columnBitmasks.put("groupId", 4L);

		columnBitmasks.put("companyId", 8L);

		columnBitmasks.put("userId", 16L);

		columnBitmasks.put("userName", 32L);

		columnBitmasks.put("createDate", 64L);

		columnBitmasks.put("modifiedDate", 128L);

		columnBitmasks.put("name", 256L);

		columnBitmasks.put("assetModel", 512L);

		columnBitmasks.put("purchaseDate", 1024L);

		columnBitmasks.put("serialNo", 2048L);

		columnBitmasks.put("status", 4096L);

		columnBitmasks.put("roomAssigned", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private Asset _escapedModel;

}